#! /bin/bash

uglifyjs   js/global.js js/i18n.js js/utils.js js/config.js js/filter.js js/fileuploader3.js js/subforms.js js/anagrafica2.js js/multifields.js js/map.js js/interactiveMap.js js/main.js  -o js/turisticgis.min.js

uglifyjs   modules/leaflet-locatecontrol/src/L.Control.Locate.js modules/leaflet-sidebar/L.Control.Sidebar.js modules/Leaflet.draw/dist/leaflet.draw.js modules/Leaflet.FileLayer/leaflet.filelayer.js modules/Leaflet.FileLayer/togeojson/togeojson.js modules/leaflet.bouncemarker/bouncemarker.js -o modules/leaflet_plugins.min.js

uglifyjs   modules/jQuery-File-Upload-9.5.7/js/jquery.iframe-transport.js modules/jQuery-File-Upload-9.5.7/js/jquery.fileupload.js modules/jQuery-File-Upload-9.5.7/js/jquery.fileupload-process.js modules/jQuery-File-Upload-9.5.7/js/jquery.fileupload-image.js modules/jQuery-File-Upload-9.5.7/js/jquery.fileupload-audio.js modules/jQuery-File-Upload-9.5.7/js/jquery.fileupload-video.js modules/jQuery-File-Upload-9.5.7/js/jquery.fileupload-validate.js	modules/jquery.fileDownload.js -o modules/jquery_filedownload.min.js

uglifyjs   modules/Gritter-master/js/jquery.gritter.min.js modules/noty-master/js/noty/jquery.noty.js modules/noty-master/js/noty/layouts/top.js modules/noty-master/js/noty/layouts/topCenter.js modules/noty-master/js/noty/layouts/topRight.js modules/noty-master/js/noty/layouts/topLeft.js modules/noty-master/js/noty/themes/default.js -o modules/noty.min.js

cat modules/jquery-ui-1.10.3/themes/base/minified/jquery-ui.min.css modules/bootstrap-3.2.0/css/bootstrap.min.css modules/Gallery-2.15.1/css/blueimp-gallery.min.css modules/Gallery-2.15.1/css/blueimp-gallery-indicator.css modules/Gallery-2.15.1/css/blueimp-gallery-video.css modules/font-awesome/css/font-awesome.min.css modules/font-awesome/css/font-awesome-ie7.min.css modules/fullcalendar-1.6.1/fullcalendar/fullcalendar.css modules/chosen_v1.0.0/chosen.css modules/leaflet-0.7.3/leaflet.css modules/leaflet-locatecontrol/src/L.Control.Locate.css  modules/leaflet-sidebar/L.Control.Sidebar.css modules/Leaflet.draw/dist/leaflet.draw.css modules/jQuery-File-Upload-9.5.7/css/jquery.fileupload.css modules/jQuery-File-Upload-9.5.7/css/jquery.fileupload-ui.css modules/jWizard/jquery.jWizard.css modules/brunob-leaflet.fullscreen-e47142c/Control.FullScreen.css modules/Gritter-master/css/jquery.gritter.css modules/DataTables-1.9.4/media/css/jquery.dataTables.css modules/jquery-timepicker/jquery.timepicker.css css/style.css css/layout.css | cssmin > css/turisticgis_all.min.css