<?php defined('SYSPATH') or die('No direct script access.');

return array(
    'title_default' => 'TrailManager',
    'main_tpl' => 'main',
    'mobile_main_tpl' => 'mobile/main',
    'img_path' => 'public/img/',
    'logo_ico' => 'trail_ico.ico',
    'logo_main' => 'logo_trail_50h.png',
    'logo_navbar' => 'logo_trail_40h.png',
    'logo_print' => 'logo_trail_50h.png',
    'logo_email' => 'logo_trail_30h.png',
    'css_compile' => FALSE,
    'css_path' => 'public/css/',
    'css_base' => array(
        '../modules/jquery-ui-1.10.3/themes/base/minified/jquery-ui.min.css' => 'screen',
        //'../modules/bootstrap3/css/bootstrap.min.css' => 'screen',
        //'../modules/bootstrap-3.1.1/css/bootstrap.min.css' => 'screen',
        '../modules/bootstrap-3.2.0/css/bootstrap.min.css' => 'screen',
        '../modules/Gallery-2.15.1/css/blueimp-gallery.min.css' => 'screen',
        '../modules/Gallery-2.15.1/css/blueimp-gallery-indicator.css' => 'screen',
        '../modules/Gallery-2.15.1/css/blueimp-gallery-video.css' => 'screen',
        //'../modules/bootstrap-modal/css/bootstrap-modal-bs3patch.css' => 'screen',
        //'../modules/bootstrap-modal/css/bootstrap-modal.css' => 'screen',
        //'../modules/AnimatedContentMenu/css/style.css' => 'screen',
        //'../modules/bootstrap3/css/bootstrap-theme.min.css' => 'screen',
        '../modules/font-awesome/css/font-awesome.min.css' => 'screen',
        '../modules/font-awesome/css/font-awesome-ie7.min.css' => 'screen',
        '../modules/fullcalendar-1.6.1/fullcalendar/fullcalendar.css' => 'screen',
        //'../modules/croppic/croppic.css' => 'screen',
        //'../modules/pikachoose/styles/bottom.css' => 'screen',
        '../modules/chosen_v1.0.0/chosen.css' => 'screen',
        '../modules/leaflet-0.7.3/leaflet.css' => 'screen',
        '../modules/leaflet-locatecontrol/src/L.Control.Locate.css' => 'screen',		
        '../modules/leaflet-sidebar/L.Control.Sidebar.css' => 'screen',
        '../modules/Leaflet.draw/dist/leaflet.draw.css' => 'screen',
		'../modules/Leaflet.defaultextent/dist/leaflet.defaultextent.css' => 'screen',
        //'../modules/pixelmatrix-uniform-3e9cd85/themes/default/css/uniform.default.css' => 'screen',
        '../modules/jQuery-File-Upload-9.5.7/css/jquery.fileupload.css' => 'screen',
        '../modules/jQuery-File-Upload-9.5.7/css/jquery.fileupload-ui.css' => 'screen',
        '../modules/jWizard/jquery.jWizard.css' => 'screen',
        '../modules/brunob-leaflet.fullscreen-e47142c/Control.FullScreen.css' => 'screen',
        //'../modules/elfinder-2.0-rc1/css/elfinder.min.css' => 'screen',
        '../modules/Gritter-master/css/jquery.gritter.css' => 'screen',
        '../modules/DataTables-1.9.4/media/css/jquery.dataTables.css' => 'screen',
        '../modules/jquery-timepicker/jquery.timepicker.css' => 'screen',
        //'../modules/jquery_layout/layout-default-latest.css' => 'screen',
        'style.css' => 'screen',
        'layout.css' => 'screen',
    ),
    'css_compiled' => array(
        'turisticgis_all.min.css' => 'screen',
    ),
   
    
);
